version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=core.server
      - FLASK_ENV=development
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
