"""Initial migration

Revision ID: 607fb9508091
Revises: 52a401750a76
Create Date: 2025-01-28 23:24:31.303744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607fb9508091'
down_revision = '52a401750a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###
